
version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongodb-container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  parser:
    build: ./parser
    container_name: parser
    env_file:
      - .env
    depends_on:
      - mongodb
    volumes:
      - ./logs:/app/logs
    command: ["python", "parser_selected_fields.py"]

  streamlit:
    build: ./app
    container_name: streamlit
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - mongodb
    command: ["streamlit", "run", "app.py", "--server.enableCORS=false", "--server.address=0.0.0.0"]