
version: '3.8'

services:
  streamlit:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: streamlit
    ports:
      - "8501:8501"
    env_file:
      - .env
    command: ["streamlit", "run", "app.py", "--server.enableCORS=false", "--server.address=0.0.0.0"]
